library(shiny)
library(ggplot2)
# UI details for mapping international migration app
shinyUI(fluidPage(theme = "bootstrap.css",
  # App title
  title="Mapping international migration flows from UN stock migrants data",
  h3("Mapping international migration flows from UN stock migrants data"),
  ## row for input and basic numbers output
  fluidRow(
    column(2,
    selectInput("country", "Select region",
                c('Afghanistan' = 'AF',
                  'Albania' = 'AL',
                  'Algeria' = 'DZ',
                  'American Samoa' = 'AS',
                  'Andorra' = 'AD',
                  'Angola' = 'AO',
                  'Anguilla' = 'AI',
                  'Antigua and Barbuda' = 'AG',
                  'Argentina' = 'AR',
                  'Armenia' = 'AM',
                  'Aruba' = 'AW',
                  'Australia' = 'AU',
                  'Austria' = 'AT',
                  'Azerbaijan' = 'AZ',
                  'Bahamas' = 'BS',
                  'Bahrain' = 'BH',
                  'Bangladesh' = 'BD',
                  'Barbados' = 'BB',
                  'Belarus' = 'BY',
                  'Belgium' = 'BE',
                  'Belize' = 'BZ',
                  'Benin' = 'BJ',
                  'Bermuda' = 'BM',
                  'Bhutan' = 'BT',
                  'Bolivia (Plurinational State of)' = 'BO',
                  'Bosnia and Herzegovina' = 'BA',
                  'Botswana' = 'BW',
                  'Brazil' = 'BR',
                  'British Virgin Islands' = 'VG',
                  'Brunei Darussalam' = 'BN',
                  'Bulgaria' = 'BG',
                  'Burkina Faso' = 'BF',
                  'Burundi' = 'BI',
                  'Cambodia' = 'KH',
                  'Cameroon' = 'CM',
                  'Canada' = 'CA',
                  'Cape Verde' = 'CV',
                  'Caribbean Netherlands' = 'BQ',
                  'Cayman Islands' = 'KY',
                  'Central African Republic' = 'CF',
                  'Chad' = 'TD',
                  'Channel Islands' = 'JE',
                  'Chile' = 'CL',
                  'China' = 'CN',
                  'China, Hong Kong Special Administrative Region' = 'HK',
                  'China, Macao Special Administrative Region' = 'MO',
                  'Colombia' = 'CO',
                  'Comoros' = 'KM',
                  'Congo' = 'CG',
                  'Cook Islands' = 'CK',
                  'Costa Rica' = 'CR',
                  "Côte d'Ivoire" = 'CI',
                  'Croatia' = 'HR',
                  'Cuba' = 'CU',
                  'Curaçao' = 'CW',
                  'Cyprus' = 'CY',
                  'Czech Republic' = 'CZ',
                  "Democratic People's Republic of Korea" = 'KP',
                  'Democratic Republic of the Congo' = 'CD',
                  'Denmark' = 'DK',
                  'Djibouti' = 'DJ',
                  'Dominica' = 'DM',
                  'Dominican Republic' = 'DO',
                  'Ecuador' = 'EC',
                  'Egypt' = 'EG',
                  'El Salvador' = 'SV',
                  'Equatorial Guinea' = 'GQ',
                  'Eritrea' = 'ER',
                  'Estonia' = 'EE',
                  'Ethiopia' = 'ET',
                  'Faeroe Islands' = 'FO',
                  'Falkland Islands (Malvinas)' = 'FK',
                  'Fiji' = 'FJ',
                  'Finland' = 'FI',
                  'France' = 'FR',
                  'French Guiana' = 'GF',
                  'French Polynesia' = 'PF',
                  'Gabon' = 'GA',
                  'Gambia' = 'GM',
                  'Georgia' = 'GE',
                  'Germany' = 'DE',
                  'Ghana' = 'GH',
                  'Gibraltar' = 'GI',
                  'Greece' = 'GR',
                  'Greenland' = 'GL',
                  'Grenada' = 'GD',
                  'Guadeloupe' = 'GP',
                  'Guam' = 'GU',
                  'Guatemala' = 'GT',
                  'Guinea' = 'GN',
                  'Guinea-Bissau' = 'GW',
                  'Guyana' = 'GY',
                  'Haiti' = 'HT',
                  'Holy See' = 'VA',
                  'Honduras' = 'HN',
                  'Hungary' = 'HU',
                  'Iceland' = 'IS',
                  'India' = 'IN',
                  'Indonesia' = 'ID',
                  'Iran (Islamic Republic of)' = 'IR',
                  'Iraq' = 'IQ',
                  'Ireland' = 'IE',
                  'Isle of Man' = 'IM',
                  'Israel' = 'IL',
                  'Italy' = 'IT',
                  'Jamaica' = 'JM',
                  'Japan' = 'JP',
                  'Jordan' = 'JO',
                  'Kazakhstan' = 'KZ',
                  'Kenya' = 'KE',
                  'Kiribati' = 'KI',
                  'Kuwait' = 'KW',
                  'Kyrgyzstan' = 'KG',
                  "Lao People's Democratic Republic" = 'LA',
                  'Latvia' = 'LV',
                  'Lebanon' = 'LB',
                  'Lesotho' = 'LS',
                  'Liberia' = 'LR',
                  'Libya' = 'LY',
                  'Liechtenstein' = 'LI',
                  'Lithuania' = 'LT',
                  'Luxembourg' = 'LU',
                  'Madagascar' = 'MG',
                  'Malawi' = 'MW',
                  'Malaysia' = 'MY',
                  'Maldives' = 'MV',
                  'Mali' = 'ML',
                  'Malta' = 'MT',
                  'Marshall Islands' = 'MH',
                  'Martinique' = 'MQ',
                  'Mauritania' = 'MR',
                  'Mauritius' = 'MU',
                  'Mayotte' = 'YT',
                  'Mexico' = 'MX',
                  'Micronesia (Federated States of)' = 'FM',
                  'Monaco' = 'MC',
                  'Mongolia' = 'MN',
                  'Montenegro' = 'ME',
                  'Montserrat' = 'MS',
                  'Morocco' = 'MA',
                  'Mozambique' = 'MZ',
                  'Myanmar' = 'MM',
                  'Namibia' = 'NA',
                  'Nauru' = 'NR',
                  'Nepal' = 'NP',
                  'Netherlands' = 'NL',
                  'New Caledonia' = 'NC',
                  'New Zealand' = 'NZ',
                  'Nicaragua' = 'NI',
                  'Niger' = 'NE',
                  'Nigeria' = 'NG',
                  'Niue' = 'NU',
                  'Northern Mariana Islands' = 'MP',
                  'Norway' = 'NO',
                  'Oman' = 'OM',
                  'Pakistan' = 'PK',
                  'Palau' = 'PW',
                  'Panama' = 'PA',
                  'Papua New Guinea' = 'PG',
                  'Paraguay' = 'PY',
                  'Peru' = 'PE',
                  'Philippines' = 'PH',
                  'Poland' = 'PL',
                  'Portugal' = 'PT',
                  'Puerto Rico' = 'PR',
                  'Qatar' = 'QA',
                  'Republic of Korea' = 'KR',
                  'Republic of Moldova' = 'MD',
                  'Réunion' = 'RE',
                  'Romania' = 'RO',
                  'Russian Federation' = 'RU',
                  'Rwanda' = 'RW',
                  'Saint Helena' = 'SH',
                  'Saint Kitts and Nevis' = 'KN',
                  'Saint Lucia' = 'LC',
                  'Saint Pierre and Miquelon' = 'PM',
                  'Saint Vincent and the Grenadines' = 'VC',
                  'Samoa' = 'WS',
                  'San Marino' = 'SM',
                  'Sao Tome and Principe' = 'ST',
                  'Saudi Arabia' = 'SA',
                  'Senegal' = 'SN',
                  'Serbia' = 'RS',
                  'Seychelles' = 'SC',
                  'Sierra Leone' = 'SL',
                  'Singapore' = 'SG',
                  'Sint Maarten (Dutch part)' = 'SX',
                  'Slovakia' = 'SK',
                  'Slovenia' = 'SI',
                  'Solomon Islands' = 'SB',
                  'Somalia' = 'SO',
                  'South Africa' = 'ZA',
                  'South Sudan' = 'SS',
                  'Spain' = 'ES',
                  'Sri Lanka' = 'LK',
                  'State of Palestine' = 'PS',
                  'Sudan' = 'SD',
                  'Suriname' = 'SR',
                  'Swaziland' = 'SZ',
                  'Sweden' = 'SE',
                  'Switzerland' = 'CH',
                  'Syrian Arab Republic' = 'SY',
                  'Tajikistan' = 'TJ',
                  'Thailand' = 'TH',
                  'The former Yugoslav Republic of Macedonia' = 'MK',
                  'Timor-Leste' = 'TL',
                  'Togo' = 'TG',
                  'Tokelau' = 'TK',
                  'Tonga' = 'TO',
                  'Trinidad and Tobago' = 'TT',
                  'Tunisia' = 'TN',
                  'Turkey' = 'TR',
                  'Turkmenistan' = 'TM',
                  'Turks and Caicos Islands' = 'TC',
                  'Tuvalu' = 'TV',
                  'Uganda' = 'UG',
                  'Ukraine' = 'UA',
                  'United Arab Emirates' = 'AE',
                  'United Kingdom of Great Britain and Northern Ireland' = 'GB',
                  'United Republic of Tanzania' = 'TZ',
                  'United States of America' = 'US',
                  'United States Virgin Islands' = 'VI',
                  'Uruguay' = 'UY',
                  'Uzbekistan' = 'UZ',
                  'Vanuatu' = 'VU',
                  'Venezuela (Bolivarian Republic of)' = 'VE',
                  'Viet Nam' = 'VN',
                  'Wallis and Futuna Islands' = 'WF',
                  'Western Sahara' = 'EH',
                  'Yemen' = 'YE',
                  'Zambia' = 'ZM',
                  'Zimbabwe' = 'ZW',
                  selected=NULL)),
selectInput("maptheme", "Select map theme",
            c("Dark", "Light",
              selected=NULL))
),
column(1,
    radioButtons("radio", "Select year",
                choices = list("2013" = 2013,
                               "2010" = 2010,
                               "2000" = 2000,
                               "1990" = 1990
                               ))
  ),
column(3,
       sliderInput('summaryRows', 'Select number of rows for summary output',
                   min=1, max=20,
                   value=5, step=1)
),
column(2,
       verbatimTextOutput("oid1")
),
column(2,
       verbatimTextOutput("oid2")
),
column(2,
       verbatimTextOutput("oid3")
)

),

  ##Main panel to display some migration statistics on the selected region and
  ##  map of in and out migrants from the region

#          h3("Stock migrant map"),
         plotOutput("mapPlot"),

fluidRow(
  column(6,
h4("Top destination regions"),
tableOutput("outSummary")),
  column(6,
         h4("Top source regions"),
         tableOutput("inSummary"))),
          h4("Documentation"),
p("This app is aimed at computing the number of migrant stocks of the selected region and visualizing the data by connecting migrant origin and destination with great circle arcs. Select the region or country from the drop down box to update the map and data output. The map theme input changes the colour styles for the output map. The data for four years are available. A summary of top destinations of migrants from the selected region and top source for migrants in the region are displayed as tables. Select the number of top regions to display using the slider. The origin and destination of the arcs are coloured differently to visualize the direction of movement. This app uses quite a large amount of memory when visualizing large number of arcs so please be patient and allow ample time for the map to get updated."),
p("The region / country names are entirely based on the United Nations data (see data sources for detail)."),
         p("Number of lines between two regions based on log of migrants between the two regions. Migrant origin shown in green and migrant destination shown in red. Locations within region selected among the top 15 most populated cities in the region with probability based on the population i.e. cities with higher population are more likely to get selected. The origin and destination of arcs are computed in each run so the maps will vary each time."),
h4("Data sources"),         
p("Data sources: Migration data from United Nations, Department of Economic and Social Affairs, Population Division (2013). Trends in International Migrant Stock: Migrants by Destination and Origin (United Nations database, POP/DB/MIG/Stock/Rev.2013) downloaded from http://esa.un.org/unmigration/TIMSA2013/data/UN_MigrantStock_2013.xls. World map shapefile from NaturalEarthData.com. Location and population of cities from geonames.org.")
  
    
  )
)